server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kakaotalkgift?serverTimezone=Asia/Seoul
    username: root
    password: 12345